In [1]:
#Implementation of Perceptron

In [51]:
import pandas as pd
import numpy as np
import os

In [52]:
class perceptron:
    def __init__(self,eta,epochs):
        self.weights = np.random.randn(3)*1e-4 #small weights initialization
        print(f"Initial weights: \n {self.weights}")
        self.eta = eta #Learning Rate
        self.epochs = epochs #Iterations
    
    def activationfunction(self,inputs,weights):
        z = np.dot(inputs,weights) #z = w1.x1+w2.x2+w0.x0
        return np.where(z > 0, 1, 0)
    
    def fit(self,X,y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X,-np.ones((len(self.X),1))] #concatinate x with bias
        print(f"X with Bias: \n {X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch: \n {epoch}")
            print("--"*10)
            
            y_hat = self.activationfunction(X_with_bias,self.weights) #forward propagation
            print(f"predicted value after forward propagation:\n {y_hat}")
            self.error = self.y - y_hat
            print(f"Error: \n {self.error}")
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error) #backward propagation
            print(f"updated weight after {epoch}/{self.epochs} : {self.weights}")
            print("####"*10)
        
        
    def predict(self,X):
        
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        return self.activationfunction(X_with_bias,self.weights)
    
    def totalloss(self):
        total_loss = np.sum(self.error)
        print(f"Total Loss: {total_loss}")
        return total_loss

In [53]:
def prepare_data(df):
    X = df.drop("y",axis=1)
    y= df['y']
    return X, y

In [33]:
AND = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,0,0,1]
}

df = pd.DataFrame(AND)
df

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [34]:
X, y = prepare_data(df)
ETA = 0.3
EPOCHS = 10

model = perceptron(eta=ETA,epochs=EPOCHS)
model.fit(X,y)

_ = model.totalloss

Initial weights: 
 [-1.36209403e-04 -1.38871399e-04  1.51276361e-05]
X with Bias: 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch: 
 0
--------------------
predicted value after forward propagation:
 [0 0 0 0]
Error: 
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weight after 0/10 : [ 0.29986379  0.29986113 -0.29998487]
########################################
--------------------
for epoch: 
 1
--------------------
predicted value after forward propagation:
 [1 1 1 1]
Error: 
 0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weight after 1/10 : [-1.36209403e-04 -1.38871399e-04  6.00015128e-01]
########################################
--------------------
for epoch: 
 2
--------------------
predicted value after forward propagation:
 [0 0 0 0]
Error: 
 0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weight after 2/10 : [0.29986379 0.29986113 0.30001513]
########################################
---------------

In [41]:
model.predict([[1,1]])

array([1])

In [43]:
OR = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,1,1,1]
}

df = pd.DataFrame(OR)
df

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [44]:
X, y = prepare_data(df)
ETA = 0.3
EPOCHS = 10

model = perceptron(eta=ETA,epochs=EPOCHS)
model.fit(X,y)

_ = model.totalloss()

Initial weights: 
 [ 2.11159864e-05 -9.40454703e-05 -1.16317828e-05]
X with Bias: 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch: 
 0
--------------------
predicted value after forward propagation:
 [1 0 1 0]
Error: 
 0   -1
1    1
2    0
3    1
Name: y, dtype: int64
updated weight after 0/10 : [ 0.30002112  0.59990595 -0.30001163]
########################################
--------------------
for epoch: 
 1
--------------------
predicted value after forward propagation:
 [1 1 1 1]
Error: 
 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weight after 1/10 : [ 3.00021116e-01  5.99905955e-01 -1.16317828e-05]
########################################
--------------------
for epoch: 
 2
--------------------
predicted value after forward propagation:
 [1 1 1 1]
Error: 
 0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weight after 2/10 : [0.30002112 0.59990595 0.29998837]
########################################
---------------

In [47]:
model.predict([[0,1]])

array([1])

In [49]:
XOR = {
    'x1':[0,0,1,1],
    'x2':[0,1,0,1],
    'y':[0,1,1,0]
}

df = pd.DataFrame(XOR)
df

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [50]:
X, y = prepare_data(df)
ETA = 0.3
EPOCHS = 10

model = perceptron(eta=ETA,epochs=EPOCHS)
model.fit(X,y)

_ = model.totalloss()

Initial weights: 
 [ 1.21359621e-04 -2.07713295e-05  3.12869334e-05]
X with Bias: 
 [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch: 
 0
--------------------
predicted value after forward propagation:
 [0 0 1 1]
Error: 
 0    0
1    1
2    0
3   -1
Name: y, dtype: int64
updated weight after 0/10 : [-2.99878640e-01 -2.07713295e-05  3.12869334e-05]
########################################
--------------------
for epoch: 
 1
--------------------
predicted value after forward propagation:
 [0 0 0 0]
Error: 
 0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weight after 1/10 : [ 1.21359621e-04  2.99979229e-01 -5.99968713e-01]
########################################
--------------------
for epoch: 
 2
--------------------
predicted value after forward propagation:
 [1 1 1 1]
Error: 
 0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weight after 2/10 : [-2.99878640e-01 -2.07713295e-05  3.12869334e-05]
#############################